/*
 * TIMER_config.h
 *
 * Created: 7/22/2024 7:22:02 PM
 *  Author: FaRaH
 */ 


#ifndef TIMER_CONFIG_H_
#define TIMER_CONFIG_H_

	/**************Timer0 Config***************/
	#define TIMER0_WAVEFORM_GENERATION_MODE		TIMER_NORMAL_MODE
	#define TIMER0_PRESCALER		TIMER_DIVISION_FACTOR_8
	
	#if TIMER0_WAVEFORM_GENERATION_MODE == TIMER_NORMAL_MODE

		#define TIMER0_PRELOAD_VAL					192
		#define TIMER0_OVERFLOW_INTERRUPT			ENABLE

	#elif TIMER0_WAVEFORM_GENERATION_MODE == TIMER0_PWM_MODE

		#define TIMER0_CTC_VAL						250
		#define TIMER0_CTC_PWM_MODE						TIMER_SET_ON_CTC_CLR_ON_TOP

	#elif TIMER0_WAVEFORM_GENERATION_MODE == TIMER_CTC_MODE

		#define TIMER0_CTC_VAL						125
		#define TIMER0_OC0_MODE						TIMER_OC_DISCONNECTED
		#define TIMER0_CTC_INTERRUPT			ENABLE

	#elif TIMER0_WAVEFORM_GENERATION_MODE == TIMER_FAST_PWM_MODE

		#define TIMER0_CTC_VAL						0
		#define TIMER0_CTC_PWM_MODE					TIMER_CLR_ON_CTC_SET_ON_TOP

	#else
		#error "Wrong TIMER0_WAVEFORM_GENERATION_MODE Config"

	#endif

	/**************Timer1 Config***************/
	#define TIMER1_WAVEFORM_GENERATION_MODE		TIMER1_FAST_PWM_ICR1_MODE
	#define TIMER1_PRESCALER					TIMER_DIVISION_FACTOR_8
	#define TIMER1_PRELOAD_VAL					0
	#define TIMER1_CTCA_VAL						500
	#define TIMER1_CTCB_VAL						0
	#define TIMER1_ICR1_VAL						20000
	#define TIMER1_OCR1A_MODE					TIMER_CLR_ON_CTC_SET_ON_TOP
	#define TIMER1_OCR1B_MODE					TIMER_CLR_ON_CTC_SET_ON_TOP
	#define TIMER1_ICR_NOISE_CANCELER			DISABLE
	#define TIMER1_ICR_EDGE				RISING_EDGE
	#define TIMER1_OVERFLOW_INTERRUPT			DISABLE
	#define TIMER1_CTCB_INTERRUPT			DISABLE
	#define TIMER1_CTCA_INTERRUPT			DISABLE
	#define TIMER1_ICR_INTERRUPT			DISABLE
	
	
	/**************Timer2 Config***************/
	#define TIMER2_WAVEFORM_GENERATION_MODE		TIMER_CTC_MODE
	#define TIMER2_PRESCALER		TIMER_DIVISION_FACTOR_64
	
	#if TIMER2_WAVEFORM_GENERATION_MODE == TIMER_NORMAL_MODE
	
		#define TIMER2_PRELOAD_VAL					192
		#define TIMER2_OVERFLOW_INTERRUPT			ENABLE

	#elif TIMER2_WAVEFORM_GENERATION_MODE == TIMER_PWM_MODE
	
		#define TIMER2_CTC_VAL						250
		#define TIMER2_CTC_PWM_MODE						TIMER_SET_ON_CTC_CLR_ON_TOP

	#elif TIMER2_WAVEFORM_GENERATION_MODE == TIMER_CTC_MODE
	
		#define TIMER2_CTC_VAL						125
		#define TIMER2_OC2_MODE						TIMER_OC_DISCONNECTED
		#define TIMER2_CTC_INTERRUPT			ENABLE

	#elif TIMER2_WAVEFORM_GENERATION_MODE == TIMER_FAST_PWM_MODE


		#define TIMER2_CTC_VAL						0
		#define TIMER2_CTC_PWM_MODE						TIMER_CLR_ON_CTC_SET_ON_TOP

	#else
		#error "Wrong TIMER2_WAVEFORM_GENERATION_MODE Config"

	#endif

	#define TIMER_u8_ICP_INIT_STATE      TIMER_u8_ICP_RAISING_EDGE
	#define WDT_PRESCALER      WDT_PS_1_0_S
	

#endif /* TIMER_CONFIG_H_ */